# Generated by Django 5.1.1 on 2024-10-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('organizer', models.CharField(max_length=30)),
                ('subscribe', models.BooleanField(default=False)),
            ],
        ),
    ]
