# Generated by Django 5.1.1 on 2024-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='last_name')),
                ('first_name', models.CharField(max_length=50, verbose_name='first_name')),
                ('phone', models.CharField(max_length=15, verbose_name='phone')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('password', models.CharField(max_length=50, verbose_name='password')),
            ],
        ),
    ]
